compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - "@electron/*"
  - "vite"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
